package com.example.jhon.abogadosapp.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.jhon.abogadosapp.db.Abogado;
import com.example.jhon.abogadosapp.db.Titulo;

import com.example.jhon.abogadosapp.db.AbogadoDao;
import com.example.jhon.abogadosapp.db.TituloDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig abogadoDaoConfig;
    private final DaoConfig tituloDaoConfig;

    private final AbogadoDao abogadoDao;
    private final TituloDao tituloDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        abogadoDaoConfig = daoConfigMap.get(AbogadoDao.class).clone();
        abogadoDaoConfig.initIdentityScope(type);

        tituloDaoConfig = daoConfigMap.get(TituloDao.class).clone();
        tituloDaoConfig.initIdentityScope(type);

        abogadoDao = new AbogadoDao(abogadoDaoConfig, this);
        tituloDao = new TituloDao(tituloDaoConfig, this);

        registerDao(Abogado.class, abogadoDao);
        registerDao(Titulo.class, tituloDao);
    }
    
    public void clear() {
        abogadoDaoConfig.getIdentityScope().clear();
        tituloDaoConfig.getIdentityScope().clear();
    }

    public AbogadoDao getAbogadoDao() {
        return abogadoDao;
    }

    public TituloDao getTituloDao() {
        return tituloDao;
    }

}
