package com.example.jhon.abogadosapp.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.example.jhon.abogadosapp.db.Titulo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TITULO".
*/
public class TituloDao extends AbstractDao<Titulo, Long> {

    public static final String TABLENAME = "TITULO";

    /**
     * Properties of entity Titulo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property AbogadoId = new Property(3, long.class, "abogadoId", false, "ABOGADO_ID");
    };

    private Query<Titulo> abogado_AbogadoTitulosQuery;

    public TituloDao(DaoConfig config) {
        super(config);
    }
    
    public TituloDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TITULO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NOMBRE\" TEXT NOT NULL ," + // 1: nombre
                "\"DESCRIPCION\" TEXT NOT NULL ," + // 2: descripcion
                "\"ABOGADO_ID\" INTEGER NOT NULL );"); // 3: abogadoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TITULO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Titulo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
        stmt.bindString(3, entity.getDescripcion());
        stmt.bindLong(4, entity.getAbogadoId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Titulo readEntity(Cursor cursor, int offset) {
        Titulo entity = new Titulo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombre
            cursor.getString(offset + 2), // descripcion
            cursor.getLong(offset + 3) // abogadoId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Titulo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setDescripcion(cursor.getString(offset + 2));
        entity.setAbogadoId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Titulo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Titulo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "abogadoTitulos" to-many relationship of Abogado. */
    public List<Titulo> _queryAbogado_AbogadoTitulos(long abogadoId) {
        synchronized (this) {
            if (abogado_AbogadoTitulosQuery == null) {
                QueryBuilder<Titulo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AbogadoId.eq(null));
                abogado_AbogadoTitulosQuery = queryBuilder.build();
            }
        }
        Query<Titulo> query = abogado_AbogadoTitulosQuery.forCurrentThread();
        query.setParameter(0, abogadoId);
        return query.list();
    }

}
