package com.example.jhon.abogadosapp.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TITULO".
 */
public class Titulo {

    private Long id;
    /** Not-null value. */
    private String nombre;
    /** Not-null value. */
    private String descripcion;
    private long abogadoId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Titulo() {
    }

    public Titulo(Long id) {
        this.id = id;
    }

    public Titulo(Long id, String nombre, String descripcion, long abogadoId) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abogadoId = abogadoId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public long getAbogadoId() {
        return abogadoId;
    }

    public void setAbogadoId(long abogadoId) {
        this.abogadoId = abogadoId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
